apiVersion: apps/v1
kind: Deployment
metadata:
  name: vin-decoder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vin-decoder
  template:
    metadata:
      labels:
        app: vin-decoder
    spec:
      containers:
        - name: vin-decoder
          image: kbrederj/devops-practice:vin-decoder-service
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: vin-decoder
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: vin-decoder
