apiVersion: v1
kind: Service
metadata:
  name: vin-decoder
  namespace: develop
spec:
  selector:
    app: vin-decoder
  ports:
    - name: http
      targetPort: 8080
      port: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vin-decoder
  namespace: develop
  labels:
    app: vin-decoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vin-decoder
  template:
    metadata:
      labels:
        app: vin-decoder
    spec:
      containers:
        - name: vin-decoder
          image: "portus.cicd.sumelongenterprise.com/jenkins/vin-decoder/develop:latest"
      imagePullSecrets:
        - name: portus-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vin-decoder
  namespace: develop
  annotations:
    kubernetes.io/ingress.class: traefik
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: vin-decoder.develop.192.168.50.11.nip.io
      http:
        paths:
          - backend:
              service:
                name: vin-decoder
                port:
                  number: 80
            path: /
            pathType: Prefix
